<!DOCTYPE html>
<html lang="en" data-required-role="admin" class="auth-pending">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>Admin Dashboard | TIO Perfume Collection</title><link rel="stylesheet" href="style.css?v=rebuilt2"><script src="tab-guard.js?v=rebuilt2"></script></head>
<body class="admin-dashboard-body">
<header class="admin-topbar"><a href="admin.php" class="admin-brand"><img src="img/logo-header.png" alt="TIO Perfume Collection"><span>Admin Dashboard</span></a><div class="admin-user"><span id="adminGreeting">Admin</span><button type="button" class="btn btn-outline-purple btn-sm" id="adminLogout">Log Out</button></div></header>
<main class="admin-main">
<section class="admin-welcome"><div><p class="section-label">OVERVIEW</p><h1>Store Dashboard</h1><p>Orders, sales, customers, products, stock, and payments in one place.</p></div><button type="button" class="btn btn-primary" id="showAddProduct">+ Add Product</button></section>
<section class="admin-stats" id="statsGrid"></section>
<section class="admin-panel"><div class="admin-panel-head"><div><p class="section-label">ORDERS</p><h2>Recent Orders</h2></div></div><div class="table-wrap"><table class="admin-table"><thead><tr><th>Order</th><th>Customer</th><th>Payment</th><th>Total</th><th>Order Status</th><th>Payment Status</th><th>Action</th></tr></thead><tbody id="ordersTable"></tbody></table></div></section>
<section class="admin-panel"><div class="admin-panel-head"><div><p class="section-label">CATALOG</p><h2>Product Management</h2></div><span id="productCountLabel"></span></div><div id="productsAdmin" class="admin-product-list"></div></section>
</main>

<div class="modal" id="productModal" aria-hidden="true"><div class="modal-card admin-product-modal"><button type="button" class="modal-close" id="closeProductModal">×</button><h2 id="productModalTitle">Add Product</h2><p class="modal-error" id="productModalError" hidden></p><form id="productForm" enctype="multipart/form-data"><input type="hidden" name="action" value="add_product"><input type="hidden" name="product_id" value=""><div class="form-grid"><label>Product Name<input type="text" name="name" required></label><label>Category<select name="category"><option value="floral">Floral</option><option value="woody">Woody</option><option value="fresh">Fresh</option><option value="gift-sets">Gift Sets</option></select></label><label>Price<input type="number" name="price" min="1" step="0.01" required></label><label>Product Image<input type="file" name="image_file" accept="image/png,image/jpeg,image/webp"></label><label class="full-span">Description<textarea name="description" rows="3"></textarea></label><label class="add-only">Default Size<input type="text" name="size_label" value="50ml"></label><label class="add-only">Starting Stock<input type="number" name="stock_qty" min="0" value="10"></label><label class="check-label"><input type="checkbox" name="is_bestseller" value="1"> Bestseller</label><label>Bestseller Rank<input type="number" name="bestseller_rank" min="1" max="20"></label></div><button class="btn btn-primary btn-block" type="submit">Save Product</button></form></div></div>
<script>
const ctx=()=>sessionStorage.getItem('tio_tab_ctx')||'';
async function adminFetch(url,opts={}){const h=new Headers(opts.headers||{});h.set('X-Tab-Context',ctx());const r=await fetch(url,{...opts,headers:h,credentials:'same-origin'});const d=await r.json();if((r.status===401||r.status===403)&&d.redirect)location.replace(d.redirect);return d;}
const esc=s=>{const d=document.createElement('div');d.textContent=s??'';return d.innerHTML};const money=n=>'₱'+Number(n||0).toLocaleString('en-PH',{minimumFractionDigits:2,maximumFractionDigits:2});let adminData=null;
async function loadDashboard(){const d=await adminFetch('admin_api.php',{cache:'no-store'});if(!d.ok)return;adminData=d;document.getElementById('adminGreeting').textContent='Admin: '+d.admin.name;renderStats(d.stats);renderOrders(d.orders);renderProducts(d.products);}
function renderStats(s){const cards=[['Total Orders',s.orders],['Total Sales',money(s.sales)],['Customers',s.customers],['Products',s.products],['VIP Members',s.vip],['Messages',s.messages],['Low Stock',s.low_stock]];document.getElementById('statsGrid').innerHTML=cards.map(([l,v])=>`<article class="stat-card"><span>${esc(l)}</span><strong>${esc(String(v))}</strong></article>`).join('');}
function renderOrders(list){const body=document.getElementById('ordersTable');body.innerHTML=list.length?list.map(o=>`<tr><td><strong>#${o.id}</strong><small>${esc(o.placed_at)}</small></td><td>${esc(o.customer_name)}<small>${esc(o.customer_email)}</small></td><td><strong>${esc(o.payment_method.toUpperCase())}</strong>${o.payment_reference?`<small>Ref: ${esc(o.payment_reference)}</small>`:''}${o.bank_name?`<small>${esc(o.bank_name)}</small>`:''}</td><td>${money(o.total)}</td><td><select data-order-status="${o.id}">${['pending','processing','shipped','delivered','cancelled'].map(x=>`<option value="${x}" ${x===o.order_status?'selected':''}>${x}</option>`).join('')}</select></td><td><select data-payment-status="${o.id}">${['unpaid','for_verification','paid','refunded'].map(x=>`<option value="${x}" ${x===o.payment_status?'selected':''}>${x.replace('_',' ')}</option>`).join('')}</select></td><td><button class="mini-action" data-save-order="${o.id}">Save</button></td></tr>`).join(''):'<tr><td colspan="7">No orders yet.</td></tr>';}
function renderProducts(list){document.getElementById('productCountLabel').textContent=list.length+' products';document.getElementById('productsAdmin').innerHTML=list.map(p=>`<article class="admin-product-item"><div class="admin-product-main"><img src="${esc(p.image)}" alt="${esc(p.name)}"><div><h3>${esc(p.name)}</h3><p>${esc(p.category)} · ${money(p.price)}</p><small>${p.is_bestseller?'Bestseller #'+(p.bestseller_rank||'—'):'Regular product'}</small></div><div class="admin-product-actions"><button type="button" class="mini-action" data-edit-product="${p.id}">Edit</button><button type="button" class="mini-action danger" data-delete-product="${p.id}">Delete</button></div></div><div class="variant-list">${p.variants.map(v=>`<div class="variant-row"><input type="text" value="${esc(v.size_label)}" data-vsize="${v.id}"><input type="number" min="0" value="${v.stock_qty}" data-vstock="${v.id}"><button type="button" class="mini-action" data-save-variant="${v.id}">Save Stock</button></div>`).join('')}<form class="add-variant-form" data-add-variant="${p.id}"><input name="size_label" placeholder="New size e.g. 100ml" required><input name="stock_qty" type="number" min="0" value="10"><button class="mini-action" type="submit">Add Size</button></form></div></article>`).join('');}
function openProduct(p=null){const m=document.getElementById('productModal'),f=document.getElementById('productForm'),el=f.elements;f.reset();el['action'].value=p?'edit_product':'add_product';el['product_id'].value=p?p.id:'';document.getElementById('productModalTitle').textContent=p?'Edit Product':'Add Product';document.querySelectorAll('.add-only').forEach(x=>x.style.display=p?'none':'');if(p){el['name'].value=p.name;el['category'].value=p.category;el['price'].value=p.price;el['description'].value=p.description||'';el['is_bestseller'].checked=!!p.is_bestseller;el['bestseller_rank'].value=p.bestseller_rank||'';}m.classList.add('open');m.setAttribute('aria-hidden','false');}
function closeProduct(){const m=document.getElementById('productModal');m.classList.remove('open');m.setAttribute('aria-hidden','true');}
document.getElementById('showAddProduct').onclick=()=>openProduct();document.getElementById('closeProductModal').onclick=closeProduct;
document.getElementById('productForm').addEventListener('submit',async function(e){e.preventDefault();const err=document.getElementById('productModalError');err.hidden=true;const d=await adminFetch('admin_action.php',{method:'POST',body:new FormData(this)});if(d.ok){closeProduct();loadDashboard();}else{err.textContent=d.error||'Could not save product.';err.hidden=false;}});
document.addEventListener('click',async e=>{let id;if(id=e.target.dataset.editProduct){openProduct(adminData.products.find(p=>p.id==id));}if(id=e.target.dataset.deleteProduct){if(confirm('Delete this product?')){const fd=new FormData();fd.append('action','delete_product');fd.append('product_id',id);const d=await adminFetch('admin_action.php',{method:'POST',body:fd});if(d.ok)loadDashboard();else alert(d.error);}}if(id=e.target.dataset.saveVariant){const fd=new FormData();fd.append('action','update_variant');fd.append('variant_id',id);fd.append('size_label',document.querySelector(`[data-vsize="${id}"]`).value);fd.append('stock_qty',document.querySelector(`[data-vstock="${id}"]`).value);const d=await adminFetch('admin_action.php',{method:'POST',body:fd});if(d.ok)loadDashboard();else alert(d.error);}if(id=e.target.dataset.saveOrder){const fd=new FormData();fd.append('action','update_order');fd.append('order_id',id);fd.append('order_status',document.querySelector(`[data-order-status="${id}"]`).value);fd.append('payment_status',document.querySelector(`[data-payment-status="${id}"]`).value);const d=await adminFetch('admin_action.php',{method:'POST',body:fd});if(d.ok)loadDashboard();else alert(d.error);}});
document.addEventListener('submit',async e=>{const form=e.target.closest('[data-add-variant]');if(!form)return;e.preventDefault();const fd=new FormData(form);fd.append('action','add_variant');fd.append('product_id',form.dataset.addVariant);const d=await adminFetch('admin_action.php',{method:'POST',body:fd});if(d.ok)loadDashboard();else alert(d.error);});
document.getElementById('adminLogout').onclick=async()=>{if(!confirm('Log out of this admin tab?'))return;await adminFetch('logout.php',{method:'POST'});sessionStorage.removeItem('tio_tab_ctx');location.replace('login.php');};
document.addEventListener('tio-auth-ready',loadDashboard);setTimeout(()=>{if(window.TIO_AUTH)loadDashboard();},200);
</script></body></html>
