<!DOCTYPE html>
<html lang="en" data-required-role="user" class="auth-pending"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>Checkout | TIO Perfume Collection</title><link rel="stylesheet" href="style.css?v=rebuilt2"><script src="tab-guard.js?v=rebuilt2"></script></head>
<body><header class="site-header"><a href="index.php" class="brand-logo"><span class="logo-mark"><img src="img/logo-header.png" alt="TIO Perfume Collection"></span></a><nav class="main-nav"><a href="index.php">HOME</a><a href="shop.php">SHOP</a><a href="orders.php">MY ORDERS</a></nav><div class="header-icons"><div class="auth-area" id="headerAuthArea"></div><a href="cart.php" class="icon-btn bag"><span>Bag</span><b id="cartCount">0</b></a></div></header>
<main><section class="page-hero"><h1>Checkout</h1><p class="breadcrumb">Shipping details and payment method.</p></section>
<section class="section"><form id="checkoutForm" class="checkout-layout"><div class="checkout-main"><div class="checkout-card"><h2>Shipping Information</h2><label>Full Name<input type="text" name="shipping_name" required></label><label>Phone Number<input type="text" name="shipping_phone" required></label><label>Delivery Address<textarea name="shipping_address" rows="4" required></textarea></label></div>
<div class="checkout-card"><p class="section-label">PAYMENT</p><h2>Choose Payment Method</h2><p class="checkout-intro">Select how you want to pay for your order.</p><div class="payment-options">
<label class="payment-option selected"><input type="radio" name="payment_method" value="gcash" checked><span><strong>GCash</strong><small>Pay using GCash and enter the transaction reference number.</small></span></label>
<label class="payment-option"><input type="radio" name="payment_method" value="bank"><span><strong>Bank Transfer</strong><small>Transfer through your bank and enter the reference number.</small></span></label>
<label class="payment-option"><input type="radio" name="payment_method" value="cod"><span><strong>Cash on Delivery</strong><small>Pay in cash when your order is delivered.</small></span></label></div>
<div id="gcashFields" class="payment-details"><label>GCash Reference Number<input type="text" name="payment_reference" placeholder="Enter transaction reference number"></label></div>
<div id="bankFields" class="payment-details" hidden><label>Bank Name<input type="text" name="bank_name" placeholder="Enter bank name"></label><label>Bank Reference Number<input type="text" name="bank_reference" placeholder="Enter transaction reference number"></label></div>
</div></div>
<aside class="cart-summary checkout-summary"><h2>Order Summary</h2><div id="checkoutItems"></div><div class="summary-line total"><span>Total</span><strong id="checkoutTotal">₱0.00</strong></div><p class="modal-error" id="checkoutError" hidden></p><button type="submit" class="btn btn-primary btn-block" id="placeOrderBtn">Place Order</button></aside></form></section></main>
<script src="script.js?v=rebuilt2"></script><script>
const peso2=n=>'₱'+Number(n||0).toLocaleString('en-PH',{minimumFractionDigits:2,maximumFractionDigits:2});
async function loadCheckout(){const d=await apiFetch('cart_api.php',{cache:'no-store'});if(!d.ok)return;if(!d.items.length){location.replace('cart.php');return;}document.getElementById('checkoutItems').innerHTML=d.items.map(i=>`<div class="checkout-mini"><span>${escapeHtml(i.name)} × ${i.quantity}<small>${escapeHtml(i.size_label)}</small></span><strong>${peso2(i.line_total)}</strong></div>`).join('');document.getElementById('checkoutTotal').textContent=peso2(d.subtotal);}
function syncPayment(){const method=document.querySelector('input[name="payment_method"]:checked').value;document.querySelectorAll('.payment-option').forEach(x=>x.classList.toggle('selected',x.querySelector('input').checked));document.getElementById('gcashFields').hidden=method!=='gcash';document.getElementById('bankFields').hidden=method!=='bank';}
document.querySelectorAll('input[name="payment_method"]').forEach(r=>r.addEventListener('change',syncPayment));syncPayment();
document.getElementById('checkoutForm').addEventListener('submit',async function(e){e.preventDefault();const err=document.getElementById('checkoutError');err.hidden=true;const fd=new FormData(this);if(fd.get('payment_method')==='bank')fd.set('payment_reference',fd.get('bank_reference'));const btn=document.getElementById('placeOrderBtn');btn.disabled=true;btn.textContent='Placing Order...';const d=await apiFetch('place_order.php',{method:'POST',body:fd});if(d.ok){alert(`Order #${d.order_id} placed successfully.`);location.replace('orders.php');}else{err.textContent=d.error||'Could not place order.';err.hidden=false;btn.disabled=false;btn.textContent='Place Order';}});
document.addEventListener('tio-auth-ready',loadCheckout);setTimeout(()=>{if(window.TIO_AUTH)loadCheckout();},200);
</script></body></html>
